# This is a basic workflow to help you get started with Actions

name: New data-update tag

on:
    push:
        branches: [master]
        tags:
            - data-update_* # Run only when there is a "data-update_yyyy-mm-dd-hh" tag


jobs:
    # First build the new gatsby page and deploy it to gh-pages branche
    gatsby:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: enriikke/gatsby-gh-pages-action@v2
              with:
                  access-token: ${{ secrets.ACCESS_TOKEN }}
                  deploy-branch: gh-pages
                  gatsby-args: --prefix-paths
    # Now inform twitter about it (but wait for gatsby to be finished)
    tweet:
        runs-on: ubuntu-latest
        needs: gatsby
        steps:
            - uses: ethomson/send-tweet-action@v1
              with:
                  status: "Just updated my COVID-19 visualization page with the newest data from @JohnsHopkins ... Check it out at https://fezde.github.io/COVID-19 - And if you have any ideas or feedback, let me know!"
                  consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
                  consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
                  access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                  access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
