# This is a basic workflow to help you get started with Actions

name: Update page on tags (excluding data-update)

on:
  push:
    tags:
        - "*"               # Run on every tag

jobs:
    # Do a second step
    instead_of_tweet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world! This is a test
