name: Test

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install wheel
        run: pip3 install wheel
      - name: Install required libs
        run: pip3 install -r requirements.txt
      - name: Execute update
        run: ./update-test.sh
