name: Test

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for upstream
        run: git remote -v
      - name: Add upstream
        run: git remote add upstream https://github.com/CSSEGISandData/COVID-19
      - name: Check if upstream is set now
        run: git remote -v
      - name: Git fetch
        run: git fetch
      - name: Execute update
        run: ./update-test.sh
