  
name: Tweet about new page version
on: 
  push:
    branches: [ gh-pages ]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Just updated my COVID-19 visualization page with the newest data from @JohnsHopkins ... Check it out at https://fezde.github.io/COVID-19 - And if you have any ideas or feedback, let me know!"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
