name: Fetch Upstream

on:
  schedule:
    # * is a special character in YAML so you have to quote this string

    - cron:  '*/15 * * * *'

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: babel/babel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
